[profile.default]
src = 'src'
test = 'test'
out = 'out'
libs = ['lib']
remappings = [
  '@prb/contracts/=lib/prb-contracts/src/',
  'ds-test/=lib/ds-test/src/',
  'forge-std/=lib/forge-std/src/',
]
libraries = []
